export default {
    SET_PACKAGES_LIST: `SET_PACKAGES_LIST`,
    SET_RAW_PACKAGES_LIST: `SET_RAW_PACKAGES_LIST`,
    SET_PACKAGES_LOADING: `SET_PACKAGES_LOADING`,
    SET_INVENTORY_LIST: `SET_INVENTORY_LIST`,
    SET_RAW_INVENTORY_LIST: `SET_RAW_INVENTORY_LIST`,
    SET_INVENTORY_LOADING: `SET_INVENTORY_LOADING`,
}